# This file configures the analyzer...

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Kerak bo‘lsa quyidagilarni qo‘shing
    unnecessary_non_null_assertion: warning

linter:
  rules:
    # Oldingi ogohlantirishlarni o‘chirish
    curly_braces_in_flow_control_structures: false
    prefer_const_constructors: false
    
    # Yangi chiqqan info ni o‘chirish
    library_prefixes: false
